"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from timer import timer_many

@timer_many(100000)
def main():
    t = 0
    i = 1
    j = 2
    f = lambda i, j: (j, i+j)
    while i < 4000000:
        i, j = f(i, j)
        t += i if i % 2 == 0 else 0
    return t

main()

# 4613732
# 0.0069ms